name: Setup

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: '17'

      - name: Run .jar file
        run: |
          pwd
          ls
          cd ./bookstore/
          java --module-path "../lib/javafx-sdk-21.0.1/lib" --add-modules javafx.controls,javafx.fxml -jar bookstore.jar
        shell: bash
